# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # ビルドコマンドなし（HTMLを直接公開）
  command = ""
  # 公開ディレクトリ
  publish = "site"

# リダイレクト設定（オプション）
[[redirects]]
  from = "/ai"
  to = "/ai/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ヘッダー設定（セキュリティ・パフォーマンス最適化）
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
